config/routes.rb
Rails.application.routes.draw do
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  resources :users
  resources :insects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insect.rb
class Insect < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true
  validates :picture, presence: true
  validate :picture_size
  mount_uploader :picture, PictureUploader

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 4 }
  enum sex: { male: 1, female: 2, other: 0 }
  validates :sex, presence: true
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/insects_controller.rb
class InsectsController < ApplicationController

  def index
    @insects = Insect.all
    @insect  = Insect.new
  end

  def create
    @insect = Insect.new(insect_params)
    if @insect.save
      flash[:success] = "the insect scilently flied out"
      redirect_to insects_path
    else
      @insects = Insect.all
      flash[:danger] = "the insect suddenly died"
      render :index
    end
  end

  def destroy
    @insect = Insect.find(params[:id])
    if @insect.destroy
      flash[:success] = "killed"
    else
      flash[:danger] = "survived"
    end
    redirect_to insects_path
  end

  private

    def insect_params
      params.require(:insect).permit(:name, :picture)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Hello #{user.name}"
      log_in user
      redirect_to user
    else
      flash.now[:danger]  = "invalid"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Hello Kid"
      redirect_to @user
    else
      render 'static_pages/home'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "changed"
      redirect_to @user
    else
      flash.now[:danger]  = "invalid"
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :sex)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insects_helper.rb
module InsectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # log in with posted user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/insects/_insect.html.slim
.col-md-3.col-sm-4.col-xs-6.insect-box.text-center id="insect-#{insect.id}"
  p.insect-name = insect.name
  = image_tag insect.picture.url, class: "insect-img animated infinite"

  = link_to "kill", insect, class: "btn btn-default", method: :delete, data: { confirm: "really?" }

app/views/insects/index.html.slim
= render 'shared/insect_form', insect: @insect

#insects.row
  - if @insects.any?
    = render @insects
  - else
    h3 Insects became extinct

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Insects Panic!!", root_url, class: "navbar-brand"
    nav
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              span Account
              b.caret
            ul.dropdown-menu
              li = link_to "Profile", current_user
              li = link_to "Settings", edit_user_path(current_user)
              li.divider
              li = link_to "Log out", logout_path, method: :delete
        - else
          li = link_to "Log in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Insects Panic
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Autour+One'
    = stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
body
  #app.container
    - flash.each do |message_type, message|
      .alert class="alert-#{message_type}" = message
    = render 'layouts/header'
    = yield
    = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains 
      = pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_insect_form.html.slim
= form_for insect do |f|
  = render 'shared/error_messages', object: f.object

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"

  /.btn.btn-default.btn-file
    | file
  = f.file_field :picture, accept: 'image/png'

  = f.submit "add", class: "btn"

app/views/shared/_user_form.html.slim
.row
  .col-md-6.col-md-offset-3
    = form_for(user) do |f|
      = render 'shared/error_messages', object: f.object

      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"

      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control"

      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: "form-control"

      .form-group
        = f.label :sex
        #sex-boxes

          = f.label :sex, :male, value: :male, class: "sex-box" do
            = f.radio_button :sex, :male, class: "hidden sex-btn"
            = image_tag 'male.png', class: "sex-image"
            p male

          = f.label :sex, :female, value: :female, class: "sex-box" do
            = f.radio_button :sex, :female, class: "hidden sex-btn"
            = image_tag 'female.png', class: "sex-image"
            p female

          = f.label :sex, :other, value: :other, class: "sex-box" do
            = f.radio_button :sex, :other, class: "hidden sex-btn", checked: true
            = image_tag 'other.png', class: "sex-image animated infinite swing"
            p other

      = f.submit "Becoming a kid", class: "btn btn-default center-block"

app/views/static_pages/home.html.slim
h1.main-title.text-center.animated Insects Panic
p.text-center Let's enjoy this like a kid

- if logged_in?
- else
  = render 'shared/user_form', user: @user

app/views/users/_user.html.slim
li id="user-#{user.id}"
  = image_tag "#{user.sex}.png", class: "user_icon"
  = user.name

app/views/users/edit.html.slim
h1 edit your status
= render 'shared/user_form', user: @user

app/views/users/index.html.slim
= render @user

app/views/users/show.html.slim
= @user.name
= @user.sex
= image_tag "#{@user.sex}.png"